
import java.sql.Date;
import java.util.ArrayList;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;

public class GUI extends javax.swing.JFrame {

    /**
     * Creates new form GUI
     */
    
    private DefaultListModel listStatusReservation;
    private DefaultListModel listStatusWaitlist;
    private DefaultListModel listStatusFaculty;
    public GUI() {
        initComponents();
        fillFacultyBox();
        fillDateBox();
        
        listStatusReservation = new DefaultListModel();
        jListStatusReservation.setModel(listStatusReservation);
        listStatusReservation.removeAllElements();
        
        listStatusWaitlist = new DefaultListModel();
        jListStatusWaitlist.setModel(listStatusWaitlist);
        fillWaitlist();
        
        listStatusFaculty = new DefaultListModel();
        jListFacultyStatus.setModel(listStatusFaculty);
        fillRooms();
    }
    
    public void fillWaitlist() {
        ArrayList<WaitlistEntry> waitlist = WaitlistQueries.getAllWaitlist();
        listStatusWaitlist.removeAllElements();
        for (int i = 0; i < waitlist.size(); i++) {
            listStatusWaitlist.addElement("Faculty: " + waitlist.get(i).getFaculty() + "    Date: " + waitlist.get(i).getDate() + "   Seats: " + waitlist.get(i).getSeats());
        }
    }
    
    public void fillRooms() {
        ArrayList<String> room = new ArrayList<>();
        ArrayList<RoomEntry> rooms = RoomQueries.getAllPossibleRooms();
        for (int i = 0; i < rooms.size(); i++) {
            room.add(rooms.get(i).getName());
        }
        jComboBoxRoom.setModel(new javax.swing.DefaultComboBoxModel(room.toArray()));
    }
    
    public void fillDateBox() {
        jComboBoxDateReserve.setModel(new javax.swing.DefaultComboBoxModel(Dates.getAllDates().toArray()));
        jComboBoxDateStatus.setModel(new javax.swing.DefaultComboBoxModel(Dates.getAllDates().toArray()));
    }
    
    public void fillFacultyBox() {
        jComboBoxFacultyReserve.setModel(new javax.swing.DefaultComboBoxModel(Faculty.getFacultyList().toArray()));
        jComboBoxFaculty.setModel(new javax.swing.DefaultComboBoxModel(Faculty.getFacultyList().toArray()));
        jComboBoxCancelFaculty.setModel(new javax.swing.DefaultComboBoxModel(Faculty.getFacultyList().toArray()));
        
    }
    
    public void fillDateCancel() {
        ArrayList<Date> dates = new ArrayList<>();
        ArrayList<ReservationEntry> reserve = ReservationQueries.getReservationsByFaculty(jComboBoxCancelFaculty.getSelectedItem().toString());
        for (int i = 0; i < reserve.size(); i++) {
            dates.add(reserve.get(i).getDate());
        }
        jComboBoxCancelDate.setModel(new javax.swing.DefaultComboBoxModel(dates.toArray()));
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jTextFieldFacultyName = new javax.swing.JTextField();
        jButtonAddFaculty = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jComboBoxFacultyReserve = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        jComboBoxDateReserve = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        jTextFieldSeatsReserve = new javax.swing.JTextField();
        jButtonReserve = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jComboBoxDateStatus = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        jListStatusReservation = new javax.swing.JList<>();
        jButtonStatusReservation = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jListStatusWaitlist = new javax.swing.JList<>();
        jPanel5 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jTextFieldAddRoom = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jTextFieldAddSeats = new javax.swing.JTextField();
        jButtonRoomSeats = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jTextFieldAddDate = new javax.swing.JTextField();
        jButtonAddDate = new javax.swing.JButton();
        jPanel7 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jComboBoxCancelFaculty = new javax.swing.JComboBox<>();
        jLabel13 = new javax.swing.JLabel();
        jComboBoxCancelDate = new javax.swing.JComboBox<>();
        jButtonCancel = new javax.swing.JButton();
        jPanel8 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jComboBoxFaculty = new javax.swing.JComboBox<>();
        jListFacultyStatus = new javax.swing.JList<>();
        jButtonFacultyStatus = new javax.swing.JButton();
        jPanel9 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jButtonRoom = new javax.swing.JButton();
        jComboBoxRoom = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("BankGothic Lt BT", 1, 24)); // NOI18N
        jLabel1.setText("Room Scheduler");

        jLabel2.setText("Faculty Name");

        jButtonAddFaculty.setText("Add");
        jButtonAddFaculty.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAddFacultyActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(58, 58, 58)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButtonAddFaculty)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(67, 67, 67)
                        .addComponent(jTextFieldFacultyName, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(124, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jTextFieldFacultyName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(31, 31, 31)
                .addComponent(jButtonAddFaculty)
                .addContainerGap(167, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Add Faculty", jPanel1);

        jLabel3.setText("Faculty");

        jComboBoxFacultyReserve.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel4.setText("Date");

        jComboBoxDateReserve.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel5.setText("Seats");

        jButtonReserve.setLabel("Reserve");
        jButtonReserve.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonReserveActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(71, 71, 71)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButtonReserve)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5))
                        .addGap(66, 66, 66)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jComboBoxFacultyReserve, 0, 113, Short.MAX_VALUE)
                            .addComponent(jComboBoxDateReserve, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jTextFieldSeatsReserve))))
                .addContainerGap(205, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jComboBoxFacultyReserve, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel4)
                    .addComponent(jComboBoxDateReserve, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel5)
                    .addComponent(jTextFieldSeatsReserve, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jButtonReserve)
                .addContainerGap(116, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Reserve Faculty Date Seats", jPanel2);

        jLabel6.setText("Date");

        jComboBoxDateStatus.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jListStatusReservation.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(jListStatusReservation);

        jButtonStatusReservation.setText("Get Status");
        jButtonStatusReservation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonStatusReservationActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(69, 69, 69)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jButtonStatusReservation)
                        .addGroup(jPanel3Layout.createSequentialGroup()
                            .addComponent(jLabel6)
                            .addGap(79, 79, 79)
                            .addComponent(jComboBoxDateStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 339, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(82, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jComboBoxDateStatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addGap(9, 9, 9)
                .addComponent(jButtonStatusReservation)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(65, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Status Reservation by Date", jPanel3);

        jListStatusWaitlist.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane2.setViewportView(jListStatusWaitlist);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(48, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 383, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(59, 59, 59))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(72, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Status Waiting List", jPanel4);

        jLabel8.setText("Room");

        jLabel9.setText("Seats");

        jButtonRoomSeats.setText("Add");
        jButtonRoomSeats.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRoomSeatsActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(125, 125, 125)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButtonRoomSeats)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8)
                            .addComponent(jLabel9))
                        .addGap(55, 55, 55)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTextFieldAddRoom, javax.swing.GroupLayout.DEFAULT_SIZE, 121, Short.MAX_VALUE)
                            .addComponent(jTextFieldAddSeats))))
                .addContainerGap(162, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jTextFieldAddRoom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel9)
                    .addComponent(jTextFieldAddSeats, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jButtonRoomSeats)
                .addContainerGap(141, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Add Room Seats", jPanel5);

        jLabel7.setText("Date");

        jButtonAddDate.setLabel("Add");
        jButtonAddDate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAddDateActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(149, 149, 149)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButtonAddDate)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addGap(45, 45, 45)
                        .addComponent(jTextFieldAddDate, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(140, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(59, 59, 59)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jTextFieldAddDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addGap(27, 27, 27)
                .addComponent(jButtonAddDate)
                .addContainerGap(148, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Add Date", jPanel6);

        jLabel12.setText("Faculty");

        jComboBoxCancelFaculty.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboBoxCancelFaculty.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxCancelFacultyActionPerformed(evt);
            }
        });

        jLabel13.setText("Date");

        jComboBoxCancelDate.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jButtonCancel.setText("Cancel");
        jButtonCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCancelActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(126, 126, 126)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButtonCancel)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel12)
                            .addComponent(jLabel13))
                        .addGap(42, 42, 42)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jComboBoxCancelFaculty, 0, 141, Short.MAX_VALUE)
                            .addComponent(jComboBoxCancelDate, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(146, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jComboBoxCancelFaculty, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jComboBoxCancelDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13))
                .addGap(29, 29, 29)
                .addComponent(jButtonCancel)
                .addContainerGap(150, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Cancel Reservation", jPanel7);

        jLabel10.setText("Faculty");

        jComboBoxFaculty.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jListFacultyStatus.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });

        jButtonFacultyStatus.setText("Get Status");
        jButtonFacultyStatus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonFacultyStatusActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(113, 113, 113)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jListFacultyStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonFacultyStatus)
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addGap(55, 55, 55)
                        .addComponent(jComboBoxFaculty, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(128, Short.MAX_VALUE))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jComboBoxFaculty, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButtonFacultyStatus)
                .addGap(18, 18, 18)
                .addComponent(jListFacultyStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(63, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Status Faculty Member", jPanel8);

        jLabel11.setText("Room");

        jButtonRoom.setText("Drop");
        jButtonRoom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRoomActionPerformed(evt);
            }
        });

        jComboBoxRoom.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel9Layout.createSequentialGroup()
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButtonRoom))
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addGap(114, 114, 114)
                        .addComponent(jLabel11)
                        .addGap(49, 49, 49)
                        .addComponent(jComboBoxRoom, 0, 159, Short.MAX_VALUE)))
                .addGap(141, 141, 141))
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel11)
                    .addComponent(jComboBoxRoom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addComponent(jButtonRoom)
                .addContainerGap(168, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Drop Room", jPanel9);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(131, 131, 131)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jTabbedPane1)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonAddFacultyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAddFacultyActionPerformed
       
        
        if (Faculty.addFaculty(jTextFieldFacultyName.getText())) {
            JOptionPane.showMessageDialog(this, "Faculty Name Added!");
            fillFacultyBox();
            jTextFieldFacultyName.setText("");
        }
        else
            JOptionPane.showMessageDialog(this, "Faculty Name Cannot Be Added!");
        
        
    }//GEN-LAST:event_jButtonAddFacultyActionPerformed

    private void jButtonReserveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonReserveActionPerformed
        String faculty = jComboBoxFacultyReserve.getSelectedItem().toString();
        Date date = Date.valueOf(jComboBoxDateReserve.getSelectedItem().toString());
        int seats = Integer.parseInt(jTextFieldSeatsReserve.getText());
        boolean result = ReservationQueries.addReservationEntry(faculty, date, seats);
        if (result == false) {
            WaitlistQueries.addWaitlistEntry(faculty, date, seats);
            fillWaitlist();
            
        }
        
    }//GEN-LAST:event_jButtonReserveActionPerformed

    private void jButtonStatusReservationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonStatusReservationActionPerformed
        Date date = Date.valueOf(jComboBoxDateStatus.getSelectedItem().toString());
        ArrayList<ReservationEntry> reservations = ReservationQueries.getReservationsByDate(date);
        listStatusReservation.removeAllElements();
        for (int i = 0; i < reservations.size(); i++) {
            listStatusReservation.addElement("Faculty: " + reservations.get(i).getFaculty() + " Room: " + reservations.get(i).getRoom() + "   Date: " + reservations.get(i).getDate());
        }
    }//GEN-LAST:event_jButtonStatusReservationActionPerformed

    private void jButtonRoomSeatsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRoomSeatsActionPerformed
        String room = jTextFieldAddRoom.getText();
        int seats = Integer.parseInt(jTextFieldAddSeats.getText());
        RoomQueries.addRoom(room, seats);
        ArrayList<WaitlistEntry> waitlist = WaitlistQueries.getAllWaitlist();
        for (int i = 0; i < waitlist.size(); i++) {
            String faculty = waitlist.get(i).getFaculty();
            Date date = waitlist.get(i).getDate();
            seats = waitlist.get(i).getSeats();
            boolean result = ReservationQueries.addReservationEntry(faculty, date, seats);
            if (result) {
                WaitlistQueries.deleteWaitlistEntry(faculty, date);
                JOptionPane.showMessageDialog(this, "This room was reserved for a faculty!");
            }
        }
        fillRooms();
    }//GEN-LAST:event_jButtonRoomSeatsActionPerformed

    private void jButtonAddDateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAddDateActionPerformed
        Date date = Date.valueOf(jTextFieldAddDate.getText());
        Dates.addDate(date);
        
    }//GEN-LAST:event_jButtonAddDateActionPerformed

    private void jButtonFacultyStatusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonFacultyStatusActionPerformed
        String faculty = jComboBoxFaculty.getSelectedItem().toString();
        ArrayList<ReservationEntry> reservation = ReservationQueries.getReservationsByFaculty(faculty);
        
        listStatusFaculty.removeAllElements();
        for (int i = 0; i < reservation.size(); i++) {
            listStatusFaculty.addElement("Room: " + reservation.get(i).getRoom() + "    Date: " + reservation.get(i).getDate());
        }
    }//GEN-LAST:event_jButtonFacultyStatusActionPerformed

    private void jButtonRoomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRoomActionPerformed
        String room = jComboBoxRoom.getSelectedItem().toString();
        RoomQueries.dropRoom(room);
        ReservationQueries.deleteReservation(room);
        JOptionPane.showMessageDialog(this, "Room dropped!");
        ArrayList<WaitlistEntry> waitlist = WaitlistQueries.getAllWaitlist();
        boolean removed = false;
        for (int i = 0; i < waitlist.size(); i++) {
            String faculty = waitlist.get(i).getFaculty();
            Date date = waitlist.get(i).getDate();
            int seats = waitlist.get(i).getSeats();
            boolean result = ReservationQueries.addReservationEntry(faculty, date, seats);
            if (result) {
                removed = true;
                WaitlistQueries.deleteWaitlistEntry(faculty, date);
                JOptionPane.showMessageDialog(this, "A room was reserved for a faculty!");
            }
        }
        if (removed == false) 
            JOptionPane.showMessageDialog(this, "Couldn't reserve a room for the faculty!");
    }//GEN-LAST:event_jButtonRoomActionPerformed

    private void jButtonCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCancelActionPerformed
        String faculty = jComboBoxCancelFaculty.getSelectedItem().toString();
        Date date = Date.valueOf(jComboBoxCancelDate.getSelectedItem().toString());
        ReservationQueries.cancelReservation(faculty, date);
        WaitlistQueries.cancelWaitlistEntry(faculty, date);
        JOptionPane.showMessageDialog(this, "Reservation Canceled!");
        ArrayList<WaitlistEntry> waitlist = WaitlistQueries.getAllWaitlist();
        for (int i = 0; i < waitlist.size(); i++) {
            faculty = waitlist.get(i).getFaculty();
            date = waitlist.get(i).getDate();
            int seats = waitlist.get(i).getSeats();
            boolean result = ReservationQueries.addReservationEntry(faculty, date, seats);
            if (result) {
                WaitlistQueries.deleteWaitlistEntry(faculty, date);
                JOptionPane.showMessageDialog(this, "A room was reserved for a faculty!");
            }
        }
    }//GEN-LAST:event_jButtonCancelActionPerformed

    private void jComboBoxCancelFacultyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxCancelFacultyActionPerformed
        fillDateCancel();
    }//GEN-LAST:event_jComboBoxCancelFacultyActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUI().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAddDate;
    private javax.swing.JButton jButtonAddFaculty;
    private javax.swing.JButton jButtonCancel;
    private javax.swing.JButton jButtonFacultyStatus;
    private javax.swing.JButton jButtonReserve;
    private javax.swing.JButton jButtonRoom;
    private javax.swing.JButton jButtonRoomSeats;
    private javax.swing.JButton jButtonStatusReservation;
    private javax.swing.JComboBox<String> jComboBoxCancelDate;
    private javax.swing.JComboBox<String> jComboBoxCancelFaculty;
    private javax.swing.JComboBox<String> jComboBoxDateReserve;
    private javax.swing.JComboBox<String> jComboBoxDateStatus;
    private javax.swing.JComboBox<String> jComboBoxFaculty;
    private javax.swing.JComboBox<String> jComboBoxFacultyReserve;
    private javax.swing.JComboBox<String> jComboBoxRoom;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JList<String> jListFacultyStatus;
    private javax.swing.JList<String> jListStatusReservation;
    private javax.swing.JList<String> jListStatusWaitlist;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextField jTextFieldAddDate;
    private javax.swing.JTextField jTextFieldAddRoom;
    private javax.swing.JTextField jTextFieldAddSeats;
    private javax.swing.JTextField jTextFieldFacultyName;
    private javax.swing.JTextField jTextFieldSeatsReserve;
    // End of variables declaration//GEN-END:variables
}
